export const TOPICS = [
  { id: 1, name: 'abuse' },
  { id: 2, name: 'adhd' },
  { id: 3, name: 'anxiety' },
  { id: 4, name: 'autism spectrum' },
  { id: 5, name: 'bipolar' },
  { id: 6, name: 'body image' },
  { id: 7, name: 'borderline personality' },
  { id: 8, name: 'depression' },
  { id: 9, name: 'dissociation' },
  { id: 10, name: 'eating' },
  { id: 11, name: 'hearing voices' },
  { id: 12, name: 'hoarding' },
  { id: 13, name: 'hypomania' },
  { id: 14, name: 'loneliness' },
  { id: 15, name: 'ocd' },
  { id: 16, name: 'paranoia' },
  { id: 17, name: 'personality' },
  { id: 18, name: 'phobias' },
  { id: 19, name: 'postnatal/perinatal' },
  { id: 20, name: 'ptsd' },
  { id: 21, name: 'pmdd' },
  { id: 22, name: 'psychosis' },
  { id: 23, name: 'addictions' },
  { id: 24, name: 'schizoaffective' },
  { id: 25, name: 'schizophrenia' },
  { id: 26, name: 'seasonalaffective' },
  { id: 27, name: 'self esteem' },
  { id: 28, name: 'self harm' },
  { id: 29, name: 'sleep problems' },
  { id: 30, name: 'stress' },
  { id: 31, name: 'suicidal feelings' },
  { id: 32, name: 'trauma' }
];
